name: conlog
description: Console Logging Library for those who hate unstructured logging and configuration.
version: 0.0.1
author: Ray King & Ji Young Lee
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  stack_trace: "^1.6.1"
  quiver: "^0.21.4"
  darpule: "^0.2.0"
  log4dart: "^1.4.18"
  lookup_map: "^0.0.1"
  petitparser: "^1.5.1"
  serviceRegistry:
    git:
      url: https://github.com/rayk/serviceRegistry.git
      ref: release

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
